<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\Parametros;

class ParametrosController extends Admin
{
    public $TITTLE = "AdminLTE | Parametros";
    public $MODULO = "parametros.index";

    public $links;

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if ($this->USER_ROLE != 100){
            header('location: '. ROOT_PATH.'admin\\');
        }
    }


    public function listarParametros(): array
    {
        $model = new Parametros();
        $limit = 30;
        $totalRows = $model->count();
        $this->links = paginate('procesar.php','table_parametros', $limit, $totalRows)->createLinks();
        return $model->paginate($limit,null, 'id','DESC');
    }



}