<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\Municipio;
use app\model\User;

class UsersController extends Admin
{
    public string $TITTLE = 'Usuarios';
    public string $MODULO = 'usuarios.index';

    public $linksPaginate;
    public $pag = 0;

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if (!validarPermisos($this->MODULO)){
            header('location: '. ROOT_PATH.'admin\\');
        }
    }

    public function listarUsuarios(): array
    {
        $model = new User();
        $limit = numRowsPaginate();
        $this->linksPaginate = paginate('_request/UsuariosRequest.php', 'tabla_usuarios', $limit, $model->count(1))->createLinks();
        return $model->paginate($limit, null, 'role', 'DESC', 1);
    }

    public function getMunicipio($id)
    {
        $model = new Municipio();
        $municipio = $model->find($id);
        return $municipio['mini'];
    }

}