<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\User;

class UsersController extends Admin
{
    public string $TITTLE = 'AdminLTE | Usuarios';
    public string $MODULO = 'usuarios.index';

    public $linksPaginate;
    public $pag = 0;

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if (!validarPermisos($this->MODULO)){
            header('location: '. ROOT_PATH.'admin\\');
        }
    }

    public function listarUsuarios(): array
    {
        $model = new User();
        $limit = 30;
        $this->linksPaginate = paginate('procesar.php', 'tabla_usuarios', $limit, $model->count(1))->createLinks();
        return $model->paginate($limit, null, 'role', 'DESC', 1);
    }



}